services:
  app:
    build: .
    container_name: cybergator_app
    environment:
      - PYTHONPATH=/app
      - SUPABASE_DB_URL=${SUPABASE_DB_URL} 
      - NEO4J_URI=${NEO4J_URI} 
      - NEO4J_USER=${NEO4J_USER} 
      - NEO4J_PASSWORD=${NEO4J_PASSWORD} 
    volumes:
      - ./app:/app/app  # Mount the app directory
      - ./tests:/app/tests  # Mount the tests directory
      - ./pyproject.toml:/app/pyproject.toml  # Mount pyproject.toml
      - ./poetry.lock:/app/poetry.lock  # Mount poetry.lock
    ports:
      - "8000:8000"
