version: '3.8'

services:
  app:
    build: .
    container_name: cybergator_app
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: cybergator_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    restart: unless-stopped

  neo4j:
    image: neo4j:5.12
    container_name: cybergator_neo4j
    env_file:
      - .env
    ports:
      - "7474:7474"
      - "7687:7687" 
    volumes:
      - neo4j_data:/data
    environment:
      NEO4J_AUTH: "${NEO4J_USERNAME}/${NEO4J_PASSWORD}"
    restart: unless-stopped

volumes:
  pg_data:
  neo4j_data: