version: '3.8'

services:
  app:
    build: .
    container_name: cybergator_app
    env_file:
      - .env
    environment:
      SUPABASE_URL: "${SUPABASE_URL}"
      SUPABASE_KEY: "${SUPABASE_KEY}"
      SUPABASE_SERVICE_ROLE: "${SUPABASE_SERVICE_ROLE}"
      DATABASE_URL: "${DATABASE_URL}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_NAME: "${DB_NAME}"
      NEO4J_USERNAME: "${NEO4J_USERNAME}"
      NEO4J_PASSWORD: "${NEO4J_PASSWORD}"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - neo4j
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: cybergator_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    restart: unless-stopped

  neo4j:
    image: neo4j:latest
    container_name: neo4j_container
    env_file:
      - .env
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}

    restart: always

volumes:
  pg_data:
  neo4j_data:
  neo4j_logs:
