name: pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  docker-and-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache Poetry virtual environment
      uses: actions/cache@v3
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          poetry-${{ runner.os }}-

    - name: Set Environment Variables
      run: |
        echo "SUPABASE_DB_URL=${{ secrets.SUPABASE_URL }}" >> $GITHUB_ENV
        echo "NEO4J_URI=${{ secrets.NEO4J_URI }}" >> $GITHUB_ENV
        echo "NEO4J_USER=${{ secrets.NEO4J_USER }}" >> $GITHUB_ENV
        echo "NEO4J_PASSWORD=${{ secrets.NEO4J_PASSWORD }}" >> $GITHUB_ENV

    - name: Disable Poetry Virtual Envs
      run: echo "POETRY_VIRTUALENVS_CREATE=false" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install Docker Compose 
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build and Start Docker Services
      run: |
        docker-compose up -d --build 
        docker ps -a  # Debug: Show running containers
        sleep 10  # Give services time to start

    - name: Run Unit Tests & Show Coverage Report
      run: |
        docker exec cybergator_app poetry run coverage run -m unittest discover -s tests -p "*.py"
        docker exec cybergator_app poetry run coverage report -m

    - name: Debug Docker Logs (If Failure)
      if: failure()
      run: docker-compose logs

    - name: Stop and Remove Containers
      if: always()
      run: docker-compose down